baseURL = "https://bj.cxb123.cc/"
languageCode = "en-us"
title = "禅修班笔记(仅供参考请勿转发)"
theme = ["docport"]
disableToc = "false"
hasCJKLanguage = "true"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
#themeVariant = "blue"
color_main = "blue"
color_second = "#b000b0"
disableSearch = "true"

editURL = "https://github.com/zuokun2013/cxbbj/edit/main/content/"
enableGitInfo = true

[[menu.shortcuts]]
#name = "<i class='fas fa-tags'></i> Tags"
#url = "/tags"
#weight = 30

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 1
  
[server]

  [[server.headers]]
    for = "/**.html"
    [server.headers.values]
      Content-Security-Policy = "script-src localhost:1313"
      Referrer-Policy = "unsafe-url"
      Access-Control-Allow-Origin = "*"
      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"