baseURL = "https://bj.cxb123.cc/"
languageCode = "en-us"
title = "圆航的禅修班笔记(仅供参考请勿转发)"
theme = "docport"
disableToc = "false"
hasCJKLanguage = "true"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
#themeVariant = "blue"
color_main = "blue"
color_second = "#b000b0"

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 30

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 1
  
